# Generated by Django 4.1.3 on 2023-04-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(max_length=50)),
            ],
        ),
    ]
