# Generated by Django 4.1.3 on 2023-04-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='note',
            field=models.CharField(max_length=50, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование товара'),
        ),
    ]
