# Generated by Django 4.1.3 on 2023-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WB', '0002_alter_goods_article_alter_goods_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='note',
            field=models.TextField(verbose_name='Примечание'),
        ),
    ]
