# Generated by Django 4.1.3 on 2023-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WB', '0003_alter_goods_options_alter_goods_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='note',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
    ]
