# Generated by Django 4.1.3 on 2023-04-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WB', '0004_alter_goods_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='title',
            new_name='product',
        ),
    ]
